// Generated by DeclarativeComposition

namespace DCL.Test.Generated.LanguageTests {
    partial class AnonymousObjectTest {
        private Microsoft.UI.Composition.Compositor _compositor;
        
        public AnonymousObjectTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreateSpriteVisual();
            var obj2 = _compositor.CreateColorBrush();
            obj2.Color = Microsoft.UI.Colors.Red;
            obj1.Brush = obj2;
        }
    }
}
