// Generated by DeclarativeComposition

#nullable enable

namespace DCL.Test.Generated.LanguageTests {
    partial class IndependentInitializerTest {
        private Microsoft.UI.Composition.Compositor? _compositor;
        
        public void InitializeComposition(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreateSpriteVisual();
            var obj2 = _compositor.CreateColorBrush();
            obj2.Color = Windows.UI.Color.FromArgb(0xff, 0xff, 0x00, 0x00);
            obj1.Brush = obj2;
        }
    }
}
