// Generated by DeclarativeComposition

namespace DCL.Test.Generated.LanguageTests {
    partial class NamedObjectTest {
        private Microsoft.UI.Composition.Compositor _compositor;
        private Microsoft.UI.Composition.SpriteVisual _rootVisual;
        private Microsoft.UI.Composition.CompositionColorBrush backgroundVisual;
        public Microsoft.UI.Composition.SpriteVisual ForegroundVisual;

        public NamedObjectTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            _rootVisual = _compositor.CreateSpriteVisual();
            backgroundVisual = _compositor.CreateColorBrush();
            backgroundVisual.Color = Microsoft.UI.Colors.Red;
            _rootVisual.Brush = backgroundVisual;
            ForegroundVisual = _compositor.CreateSpriteVisual();
            ForegroundVisual.Size = new(100f, 100f);
            ForegroundVisual.Offset = new(0f, 0f, 0f);
            ForegroundVisual.Opacity = 0.5f;
        }
    }
}
