// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class AmbientLightTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public AmbientLightTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreateAmbientLight();
            obj1.Comment = "AmbientLight";
            obj1.IsEnabled = true;
            obj1.Color = Microsoft.UI.Colors.White;
            obj1.Intensity = 1f;
        }
    }
}