// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class BackdropBrushTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public BackdropBrushTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreateBackdropBrush();
            obj1.Comment = "BackdropBrush";
        }
    }
}