// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class BrushTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public BrushTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            // Unable to create an object with type 'Brush': No constructor or factory method found.
        }
    }
}