// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class ClipTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public ClipTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            // Unable to create an object with type 'Clip': No constructor or factory method found.
        }
    }
}