// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class ColorGradientStopTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public ColorGradientStopTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreateColorGradientStop();
            obj1.Comment = "ColorGradientStop";
            obj1.Color = Microsoft.UI.Colors.White;
            obj1.Offset = 0f;
        }
    }
}