// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class ColorBrushTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public ColorBrushTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreateColorBrush();
            obj1.Comment = "ColorBrush";
            obj1.Color = Microsoft.UI.Colors.Red;
        }
    }
}