// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class CompositionClipTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public CompositionClipTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            // Unable to create an object with type 'CompositionClip': No constructor or factory method found.
        }
    }
}