// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class CompositionShapeTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public CompositionShapeTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            // Unable to create an object with type 'CompositionShape': No constructor or factory method found.
        }
    }
}