// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class CompositionLightTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public CompositionLightTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            // Unable to create an object with type 'CompositionLight': No constructor or factory method found.
        }
    }
}