// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class CompositionGeometryTest {
        private Microsoft.UI.Composition.Compositor _compositor;
        
        public CompositionGeometryTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            // Unable to create an object with type 'CompositionGeometry': No constructor or factory method found.
        }
    }
}