// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class CompositionObjectTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public CompositionObjectTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            // Unable to create an object with type 'CompositionObject': No constructor or factory method found.
        }
    }
}