// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class CompositionBrushTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public CompositionBrushTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            // Unable to create an object with type 'CompositionBrush': No constructor or factory method found.
        }
    }
}