// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class CompositionShadowTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public CompositionShadowTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            // Unable to create an object with type 'CompositionShadow': No constructor or factory method found.
        }
    }
}