// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class DistantLightTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public DistantLightTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreateDistantLight();
            obj1.Comment = "DistantLight";
            obj1.IsEnabled = true;
            obj1.Color = Microsoft.UI.Colors.White;
            obj1.CoordinateSpace = _compositor.CreateSpriteVisual();
            obj1.Direction = new(0f, 0f, 1f);
            obj1.Intensity = 1f;
        }
    }
}