// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class DropShadowTest {
        private Microsoft.UI.Composition.Compositor _compositor;
        
        public DropShadowTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreateDropShadow();
            obj1.Comment = "DropShadow";
            obj1.BlurRadius = 4f;
            obj1.Color = Microsoft.UI.Colors.White;
            obj1.Mask = _compositor.CreateColorBrush();
            obj1.Offset = new System.Numerics.Vector3(0f, 0f, 0f);
            obj1.Opacity = 1f;
            obj1.SourcePolicy = Microsoft.UI.Composition.CompositionDropShadowSourcePolicy.Default;
        }
    }
}