// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class EffectBrushTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public EffectBrushTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreateEffectBrush();
            obj1.Comment = "EffectBrush";
        }
    }
}