// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class EffectBrushTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public EffectBrushTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            // Unable to create an object with type 'EffectBrush': No constructor or factory method found.
        }
    }
}