// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class GeometryTest {
        private Microsoft.UI.Composition.Compositor _compositor;
        
        public GeometryTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            // Unable to create an object with type 'Geometry': No constructor or factory method found.
        }
    }
}