// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class GradientBrushTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public GradientBrushTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            // Unable to create an object with type 'GradientBrush': No constructor or factory method found.
        }
    }
}