// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class InsetClipTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public InsetClipTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreateInsetClip();
            obj1.Comment = "InsetClip";
            obj1.AnchorPoint = new System.Numerics.Vector2(0f, 0f);
            obj1.CenterPoint = new System.Numerics.Vector2(0f, 0f);
            obj1.Offset = new System.Numerics.Vector2(0f, 0f);
            obj1.RotationAngle = 0f;
            obj1.RotationAngleInDegrees = 0f;
            obj1.Scale = new System.Numerics.Vector2(1f, 1f);
            obj1.TransformMatrix = new System.Numerics.Matrix3x2(1f, 0f, 0f, 1f, 0f, 0f);
            obj1.BottomInset = 0f;
            obj1.LeftInset = 0f;
            obj1.RightInset = 0f;
            obj1.TopInset = 0f;
        }
    }
}