// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class LightTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public LightTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            // Unable to create an object with type 'Light': No constructor or factory method found.
        }
    }
}