// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class LineGeometryTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public LineGeometryTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreateLineGeometry();
            obj1.Comment = "LineGeometry";
            obj1.TrimEnd = 0f;
            obj1.TrimOffset = 0f;
            obj1.TrimStart = 0f;
            obj1.End = new System.Numerics.Vector2(100f, 100f);
            obj1.Start = new System.Numerics.Vector2(0f, 0f);
        }
    }
}