// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class MaskBrushTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public MaskBrushTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreateMaskBrush();
            obj1.Comment = "MaskBrush";
            obj1.Mask = _compositor.CreateColorBrush();
            obj1.Source = _compositor.CreateColorBrush();
        }
    }
}