// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class NineGridBrushTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public NineGridBrushTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreateNineGridBrush();
            obj1.Comment = "NineGridBrush";
            obj1.BottomInset = 0f;
            obj1.BottomInsetScale = 1f;
            obj1.IsCenterHollow = true;
            obj1.LeftInset = 0f;
            obj1.LeftInsetScale = 1f;
            obj1.RightInset = 0f;
            obj1.RightInsetScale = 1f;
            obj1.Source = _compositor.CreateColorBrush();
            obj1.TopInset = 0f;
            obj1.TopInsetScale = 1f;
        }
    }
}