// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class PathGeometryTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public PathGeometryTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreatePathGeometry();
            obj1.Comment = "PathGeometry";
            obj1.TrimEnd = 0f;
            obj1.TrimOffset = 0f;
            obj1.TrimStart = 0f;
        }
    }
}