// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {

    partial class ProjectedShadowReceiverTest {

        private Microsoft.UI.Composition.Compositor _compositor;


        public ProjectedShadowReceiverTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;

            var obj1 = _compositor.CreateProjectedShadowReceiver();
            obj1.Comment = "ProjectedShadowReceiver";
            obj1.ReceivingVisual = _compositor.CreateSpriteVisual();
        }

    }

}