// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class ProjectedShadowTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public ProjectedShadowTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreateProjectedShadow();
            obj1.Comment = "ProjectedShadow";
            obj1.BlurRadiusMultiplier = 1f;
            obj1.Casters = new();
            obj1.LightSource = _compositor.CreateAmbientLight();
            obj1.MaxBlurRadius = 20f;
            obj1.MinBlurRadius = 10f;
            obj1.Receivers = new();
        }
    }
}