// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class ProjectedShadowCasterTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public ProjectedShadowCasterTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreateProjectedShadowCaster();
            obj1.Comment = "ProjectedShadowCaster";
            obj1.Brush = _compositor.CreateColorBrush();
            obj1.CastingVisual = _compositor.CreateSpriteVisual();
        }
    }
}