// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class RectangleClipTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public RectangleClipTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreateRectangleClip();
            obj1.Comment = "RectangleClip";
            obj1.AnchorPoint = new System.Numerics.Vector2(0f, 0f);
            obj1.CenterPoint = new System.Numerics.Vector2(0f, 0f);
            obj1.Offset = new System.Numerics.Vector2(0f, 0f);
            obj1.RotationAngle = 0f;
            obj1.RotationAngleInDegrees = 0f;
            obj1.Scale = new System.Numerics.Vector2(1f, 1f);
            obj1.TransformMatrix = new System.Numerics.Matrix3x2(1f, 0f, 0f, 1f, 0f, 0f);
            obj1.Bottom = 0f;
            obj1.BottomLeftRadius = new System.Numerics.Vector2(0f, 0f);
            obj1.BottomRightRadius = new System.Numerics.Vector2(0f, 0f);
            obj1.Left = 0f;
            obj1.Right = 0f;
            obj1.Top = 0f;
            obj1.TopLeftRadius = new System.Numerics.Vector2(0f, 0f);
            obj1.TopRightRadius = new System.Numerics.Vector2(0f, 0f);
        }
    }
}