// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class RectangleGeometryTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public RectangleGeometryTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreateRectangleGeometry();
            obj1.Comment = "RectangleGeometry";
            obj1.TrimEnd = 0f;
            obj1.TrimOffset = 0f;
            obj1.TrimStart = 0f;
            obj1.Offset = new(0f, 0f);
            obj1.Size = new(0f, 0f);
        }
    }
}