// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class RoundedRectangleGeometryTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public RoundedRectangleGeometryTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreateRoundedRectangleGeometry();
            obj1.Comment = "RoundedRectangleGeometry";
            obj1.TrimEnd = 0f;
            obj1.TrimOffset = 0f;
            obj1.TrimStart = 0f;
            obj1.CornerRadius = new System.Numerics.Vector2(0f, 0f);
            obj1.Offset = new System.Numerics.Vector2(0f, 0f);
            obj1.Size = new System.Numerics.Vector2(0f, 0f);
        }
    }
}