// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class ShadowTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public ShadowTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            // Unable to create an object with type 'Shadow': No constructor or factory method found.
        }
    }
}