// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class ShapeTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public ShapeTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            // Unable to create an object with type 'Shape': No constructor or factory method found.
        }
    }
}