// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class SpriteShapeTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public SpriteShapeTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreateSpriteShape();
            obj1.Comment = "SpriteShape";
            obj1.CenterPoint = new(0f, 0f);
            obj1.Offset = new(0f, 0f);
            obj1.RotationAngle = 0f;
            obj1.RotationAngleInDegrees = 0f;
            obj1.Scale = new(1f, 1f);
            obj1.TransformMatrix = new(1f, 0f, 0f, 1f, 0f, 0f);
            obj1.FillBrush = _compositor.CreateColorBrush();
            obj1.Geometry = _compositor.CreateRectangleGeometry();
            obj1.IsStrokeNonScaling = true;
            obj1.StrokeBrush = _compositor.CreateColorBrush();
            obj1.StrokeDashArray = new();
            obj1.StrokeDashCap = Microsoft.UI.Composition.CompositionStrokeCap.Flat;
            obj1.StrokeDashOffset = 0f;
            obj1.StrokeEndCap = Microsoft.UI.Composition.CompositionStrokeCap.Flat;
            obj1.StrokeLineJoin = Microsoft.UI.Composition.CompositionStrokeLineJoin.Miter;
            obj1.StrokeMiterLimit = 0f;
            obj1.StrokeStartCap = Microsoft.UI.Composition.CompositionStrokeCap.Flat;
            obj1.StrokeThickness = 1f;
        }
    }
}