// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {

    partial class ViewBoxTest {

        private Microsoft.UI.Composition.Compositor _compositor;


        public ViewBoxTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;

            var obj1 = _compositor.CreateViewBox();
            obj1.Comment = "ViewBox";
            obj1.HorizontalAlignmentRatio = 0.5f;
            obj1.Offset = new System.Numerics.Vector2(0f, 0f);
            obj1.Size = new System.Numerics.Vector2(0f, 0f);
            obj1.Stretch = Microsoft.UI.Composition.CompositionStretch.None;
            obj1.VerticalAlignmentRatio = 0.5f;
        }

    }

}