// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class VisualSurfaceTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public VisualSurfaceTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            var obj1 = _compositor.CreateVisualSurface();
            obj1.Comment = "VisualSurface";
            obj1.SourceOffset = new(0.0f, 0.0f);
            obj1.SourceSize = new(0.0f, 0.0f);
            obj1.SourceVisual = _compositor.CreateSpriteVisual();
        }
    }
}