// Generated by DeclarativeComposition

namespace DCL.Test.ProviderTests {
    partial class VisualTest {
        private Microsoft.UI.Composition.Compositor _compositor;

        public VisualTest(Microsoft.UI.Composition.Compositor compositor) {
            _compositor = compositor;
            // Unable to create an object with type 'Visual': No constructor or factory method found.
        }
    }
}